spring:
  flyway:
    url: jdbc:postgresql://localhost:5432/studycasedb
    schemas: public
    user: postgres
    password: postgres
    locations: classpath:db

---
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/studycasedb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

---
spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        hbm2ddl:
          auto: validate
        format_sql: true


---
spring:
  thymeleaf:
    check-template: true
    prefix: classpath:templates/

---
spring:
  messages:
    basename: i18n/messages

server:
  port: 8080

logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.thoughtmechanix: DEBUG